<a href="https://colab.research.google.com/github/SMushkin/FAKE-NEWS-DETECTION-SYSTEM/blob/main/CLASSIFICATION_ANALYSIS_OF_BREAST_CANCER_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv('Breast_cancer_data.csv')
print(dataset)
dataset.shape
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
y.reshape(-1,1)
print(X)
print(y)

     mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0          17.99         10.38  ...          0.11840          0
1          20.57         17.77  ...          0.08474          0
2          19.69         21.25  ...          0.10960          0
3          11.42         20.38  ...          0.14250          0
4          20.29         14.34  ...          0.10030          0
..           ...           ...  ...              ...        ...
564        21.56         22.39  ...          0.11100          0
565        20.13         28.25  ...          0.09780          0
566        16.60         28.08  ...          0.08455          0
567        20.60         29.33  ...          0.11780          0
568         7.76         24.54  ...          0.05263          1

[569 rows x 6 columns]
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 8.581e+02 8.

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

LOGISTIC REGRESSION

In [5]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [6]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [7]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [8]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
print(result)
scores=accuracy_score(y_test,y_pred)
print(np.round(scores*100,4))

[[40  3]
 [ 5 66]]
92.9825


KNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))

[[37  6]
 [ 1 70]]
93.8596


KERNEL SVM

In [10]:
from sklearn.svm import SVC
classifier=SVC(kernel='rbf',random_state=42)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))

[[34  9]
 [ 0 71]]
92.1053


NAIVE BAYES

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))


[[36  7]
 [ 0 71]]
93.8596


DECISION TREE

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',max_leaf_nodes=10,random_state=42)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))

[[41  2]
 [ 7 64]]
92.1053


RANDOM FOREST

In [13]:
from sklearn.ensemble import RandomForestClassifier
classsifier=RandomForestClassifier(max_leaf_nodes=10,random_state=42)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))


[[41  2]
 [ 7 64]]
92.1053


XGBOOST

In [20]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
res=confusion_matrix(y_test,y_pred)
print(res)
res2=accuracy_score(y_test,y_pred)
print(np.round(res2*100,4))

[[41  2]
 [ 1 70]]
97.3684
